namespace: fleet-test
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: uat
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      env: uat

- name: prod
  helm:
    values:
      serviceType: NodePort
      replicas: 1
  clusterSelector:
    matchLabels:
      env: prod
