namespace: fleet-test
targetCustomizations:
- name: k3s
  helm:
    values:
      replicas: 1
      serviceType: NodePort
  clusterSelector:
    matchLabels:
      env: k3s

- name: k3s-2
  helm:
    values:
      replicas: 1
      serviceType: NodePort
  clusterSelector:
    matchLabels:
      env: k3s-2

- name: kubeadm
  helm:
    values:
      serviceType: NodePort
      replicas: 1
  clusterSelector:
    matchLabels:
      env: kubeadm
