namespace: fleet-test
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterGroup: k3s-clusters
  clusterName: k3s

- name: uat
  helm:
    values:
      replicas: 1
  clusterGroup: k3s-clusters
  clusterName: k3s-2

- name: prod
  helm:
    values:
      serviceType: NodePort
      replicas: 2
  clusterSelector:
    matchLabels:
      env: prod
