namespace: fleet-test
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: k3s

- name: test
  helm:
    values:
      replicas: 2
  clusterSelector:
    matchLabels:
      env: k3s-2

- name: prod
  helm:
    values:
      serviceType: NodePort
      replicas: 2
  clusterSelector:
    matchLabels:
      env: kubeadm
